# Generated by Django 2.1.3 on 2016-02-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20190428_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='presente',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Unidad'), ('2', 'Kilo'), ('3', 'Litro'), ('4', 'Otros')], max_length=20),
        ),
    ]
