# Generated by Django 2.1.5 on 2019-08-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20160211_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionFactura',
        ),
        migrations.AddField(
            model_name='opciones',
            name='mensaje_factura',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='opciones',
            name='nombre_negocio',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
