# Generated by Django 2.1.3 on 2019-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_usuario_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciones',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='logo'),
        ),
    ]
