# Generated by Django 2.1.3 on 2019-11-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_opciones_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opciones',
            name='logo',
        ),
    ]
