# Generated by Django 2.1.3 on 2019-11-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20191126_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='monto_general',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sub_monto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='monto_general',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sub_monto',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
